language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
r_packages:
- covr
- AER
- aod
- betareg
- bigFastlm
- biglm
- brglm
- caret
- crch
- e1071
- earth
- ff
- ffbase
- gam
- gee
- glmnet
- glmx
- kernlab
- lme4
- MASS
- mclogit
- mda
- mlogit
- mnlogit
- MNP
- nlme
- nnet
- ordinal
- plm
- pscl
- quantreg
- rpart
- sampleSelection
- speedglm
- survey
- survival
- truncreg
- VGAM
after_success:
- R -q -e 'library("covr");codecov()'
